### ISSUE TITLE
How to add container startup criteria like programs to execute on deployment?

### ISSUE THREAD

**Issue by mydogspies** [paketo-buildpacks/java#127]
Using the standard Dockerfile build flow we can add things like COPY, CMD and most useful RUN in order to execute something on container startup. How can this be achieved with buildpacks? I have seen dockerbuild.yml mentioned but I have not been able to find any documentation on syntax or examples.

In my case I need to run the java keytool upon container start. How do I achieve this with the java buildpack?

**Comment by dmikusa-pivotal** [comment]
When specifically do you want this to run? Do you want it to run at build time when the buildpacks run & the image is being created or in the runtime container before your app starts up? It sounds like the latter, but please confirm.

**Comment by mydogspies** [comment]
Thank you so much for your reply! Yes sorry, was not specific enough. What I meant is the actual runtime on pre to container start.

**Comment by dmikusa-pivotal** [comment]
You can use a `.profile` script for this. Essentially what you do is create a bash script and name it `.profile`. The trick with this is that it needs to end up in the root of your application, i.e. what ends up in the `/workspace` directory of your final image.

For Java apps, that is tricky because we build a JAR/WAR and the contents of that are what ends up in `/workspace`. So you need to ensure that when you are building your JAR/WAR, the `.profile` script is placed into the root of the JAR. The net result is that if you can run `jar tf <jar/war-for-app>` and see `.profile` without any leading directories then it's in the right place.

I was looking for a document link that describes this and couldn't find one, sorry about that. I'll make a note to add this to our docs.

**Comment by dmikusa-pivotal** [comment]
It's been a little while. I'm going to close this out. Comment if you still have questions/issues.
