### ISSUE TITLE
Missing important CVE fixes of used BuildPacks

### ISSUE THREAD

**Issue by LeonKolataAtGov** [paketo-buildpacks/java#1530]
Please update the Java Buildpack more frequently due to upcoming CVEs in the Built Images with that.

## Expected Behavior

The Paketo Buildpack for Java should automatically update its buildpacks to the latest available versions, ensuring that security vulnerabilities (such as CVEs) are addressed promptly. The buildpacks, including the CA Certificates Buildpack, should use the latest releases (e.g., version 3.8.6) when available to ensure the build images are free of known security vulnerabilities.
##  Current Behavior

Some buildpacks, such as the CA Certificates Buildpack, are not being updated to the latest available versions (e.g., the current version in use is 3.8.4, while the CVE fix for GoLang is present in version 3.8.6). As a result, build images are triggering CVE warnings due to outdated dependencies. We are unable to manually update these buildpacks as we cannot use the PACK CLI in our environment, leading to security concerns.

## Possible Solution

Ensure that the Paketo Buildpack for Java Stack pipeline is correctly updating all buildpack dependencies, and that new versions are released frequently to address any CVEs. It may be necessary to investigate if there are issues with the current release pipeline or its frequency. Additionally, providing a manual override option for updating specific buildpacks could resolve this issue for environments like ours that do not use the PACK CLI.

## Steps to Reproduce

    Use the Paketo Buildpack for Java in a non-dockerized environment by directly invoking cnb/builder.
    Verify that the CA Certificates Buildpack version in the build image is 3.8.4.
    Check for CVE warnings related to GoLang in the build image.
    Confirm that the latest version of the CA Certificates Buildpack (3.8.6) contains the fix for the CVE but is not used in the build image.
    Observe that there is no way to manually update the buildpack version due to the inability to use the PACK CLI.

## Motivations

This issue impacts the security of our build images, as outdated dependencies with known CVEs increase the risk of vulnerabilities in production. We are trying to ensure our builds are secure and up-to-date, but without the ability to manually update buildpacks or rely on the pipeline to release updates frequently, this is difficult to achieve. This has caused delays in our development process and poses a risk to the reliability of our software in production environments.

**Comment by dmikusa** [comment]
https://github.com/orgs/paketo-buildpacks/discussions/308

It's annoying that scanners flag buildpack-generated apps as vulnerable because 99% of the time, it is a false positive. Desipte that, we look at every Go CVE reported and investigate if it will impact buildpacks. 

In a nutshell, the part of buildpacks that gets put into your actual app image (the exec.d helper binary) is very small, and mostly just reads env variables. This is why we focus on impact for these binaries and why most CVEs don't impact buildpacks in any meaningful way. 

You might be thinking, well wait, what about the buildpack itself, while the buildpack itself does have a lot more code, the truth is that there is almost always an easier way to execute something in the build container than a CVE (post-build scripts, inline buildpacks, custom buildpacks, etc...). Given that you don't need a CVE to break the build or inject something into the build, the impact of a CVE in the buildpack itself is almost never significant either.

If there is a particular CVE you're curious about, they usually come up as topics on the discussion board, like https://github.com/orgs/paketo-buildpacks/discussions/308. In the future, please open topics related to CVEs there.

-------

I do apologize that we haven't shipped a release in a little while. That's not typical, which you can see if you look back at past release dates. We typically shoot for a weekly roll-up release for each of our composite buildpacks: java, java-native-image, and java-azure. There has been a pipeline issue that has prevented this recently & we're working on getting it fixed. We hope to have a release cut as soon as that's resolved.

**Comment by LeonKolataAtGov** [comment]
Thanks for the quick response, are you able to provide any time-frame for the fix of your pipeline ?
