### ISSUE TITLE
Add custom folders during paketo build

### ISSUE THREAD

**Issue by goafabric** [paketo-buildpacks/java#662]
[note: as requested by https://github.com/paketo-buildpacks/base-builder/issues/484]
I am using paketo build packs with Spring Boot for Native Container Images + Maven.
And because of some limitations of flyway, I have the requirement to add an additional directory with content to the image.
JIb has a property "extraDirectories" to achieve this.
But diving into paketos documentation i could not find something similar.
So is there something that can be activated by some <BP_XX> Parameter ?

Otherwise i have to leverage JIB or a Dockerfile afterwards

Thank you in advance

**Comment by goafabric** [comment]
ok i guess for native images build inside docker this is a lil different, because console log tells me

/layers/paketo-buildpacks_native-image/native-image/org.***.personservice.Application (executable)

and this is maybe inside the containter ? ...

**Comment by dmikusa-pivotal** [comment]
Sorry, I was looking into this more and I don't think it's going to work presently. We are aggressively pruning files to keep the image size down. After compilation with Maven, we strip out all of the source code and after native-image compilation, we do the same with the bytecode.

For Maven and source code, you can use the argument I mentioned to ensure that stuff is retained in `/workspace`. There is not a similar option for native-image though. The buildpack removes all the bytecode and doesn't retain anything besides the image.

>ok i guess for native images build inside docker this is a lil different, because console log tells me /layers/paketo-buildpacks_native-image/native-image/org.***.personservice.Application (executable)

The `/layers` directory contains the outputs from buildpacks, they are not all carried over into the final image. When you add the option for `BP_MAVEN_BUILT_ARTIFACT` it will save the matched files to `/layers/paketo-buildpacks_maven/`, but that is only available at build time. 

I think what is needed here is a code change to the buildpack. I'd be interested in how you'd see this working. The buildpack can certainly persist files through to your final image. We could add an env variable to the native-image buildpack like `BP_NATIVE_IMAGE_ADDITIONAL_FILES` (the `BP_NATIVE_IMAGE_BUILT_ARTIFACT` is different, that points native image to a specific JAR file that we should build, in the case where you have multiple JAR files which isn't something that happens with Spring Boot apps). The env would be a space separate list of glob patterns. Anything matched, would be copied to the run image. 

The part that is a little confusing here is that buildpacks work in a pipeline fashion and they can each transform the `/workspace` directory as they execute. The `/workspace` is where your final binary is located and that is what's executed in your final image. By the time native-image runs, the contents of your `/workspace` are not the same as your source code. That means you'd have to write glob patterns that match the state of the workspace at that time. That would essentially be the set of files that you preserve through the build phase with `BP_MAVEN_BUILT_ARTIFACT`, which is not exactly intuitive.

For example:

```
.
├── README.md
├── mvnw
├── mvnw.cmd
├── pom.xml
├── src
│   ├── main
│   │   ├── java
│   │   └── resources
│   └── test
│       └── java
└── target
```

If you set `BP_MAVEN_BUILT_ARTIFACT='target/*.jar target/classes'`, then you'd end up with `target/demo-0.0.1-SNAPSHOT.jar and `target/classes/*` in the `/workspace` when native-image runs. You would then need to set `BP_NATIVE_IMAGE_BUILT_ARTIFACT=target/*.jar`, so it can find your JAR and build the native image binary from it, and then `BP_NATIVE_IMAGE_ADDITIONAL_FILES=target/classes/db/migration` so that it copies those files into the final run image. This could be a little confusing as you might expect to be able to set `src/main/resources/db/migration`.

The output of this example would be:

```
├── io.paketo.demo.DemoApplication
└── target
│   ├── classes
|    │   ├── db
|    |    │   ├── migration
...
```

Your app would have to know to look in that location for the files, which may not be where it expects them.

I'm curious to know what you would expect here? Where you'd expect files to exist? Where your app would need them to exist? etc...

This might be something that we need to address differently. There is an issue open regarding the ability to control what files are/aren't deleted, https://github.com/paketo-buildpacks/libbs/issues/103, I think the same concerns apply here. Adding a single env variable like is proposed there would probably be a better option. I still think there's questions about where stuff ends up in the final image though. If we copy `src/main/resources/db/migrations` to `/workspace/src/main/resources/db/migrations`, is that really helpful? In addition to https://github.com/paketo-buildpacks/libbs/issues/103, we might need some sort of transform option but I'm not sure what that would look like off hand.

**Comment by goafabric** [comment]
Thank you for the very detailed description and taking so much time.

**The overall abstract requirement is quiete simple.**
That would be any option similar to jibs extradirectiories
https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/README.md#extradirectories-object

This lets you define a "from path" from your project /workspace
 and and into, where to reside inside the container.
Of course both options only make sense, when the build job has acces to the "from" files.
And the application has acces to the "into folder".

** The concrete requirement in this special case **
is basically what you wrote and to copy the migrations.
This would basically be a workaround for https://github.com/spring-projects-experimental/spring-native/issues/778
Of course if spring native would/will have proper flyway support that is not needed.

Currently i simulate the behaviour by having a jib or dockerfile process the container again after paketo.
And just adding the directory .. ANd then during bootstrap tell flyway to use the migrations from the filesystem.
You can define a location there .. no problem.
All in all that works, but just chaining one hack after another

**Conclusion**
For the concrete requirement the best solution would be a solution to the flyway ticket.
But overall having some functionality like extradirectories, would help in general

**Comment by dmikusa-pivotal** [comment]
One additional note of reference for anyone coming upon this thread. In most cases, Spring Boot resources (i.e. files under `src/main/resources` should be bundled into the actual binary. The Spring Boot tooling will include resources in the `resource-config.json` that is generated, what's listed in there ends up in the binary.

**Comment by goafabric** [comment]
i see no value in this anymore 
i think for flyway we should have another solution

**Comment by dmikusa** [comment]
Just to follow up, we did end up implementing https://github.com/paketo-buildpacks/libbs/issues/103 and it was released in [7.2.0](https://github.com/paketo-buildpacks/java/releases/tag/v7.2.0). 

That does not have the transformation capabilities I mentioned, but it would allow you to keep the files through into the final container. You could get around that by having the same directory structure in your source code, that you require in the final image.

For example: if you need `/workspace/migrations`, then you would just need to have `migrations/` in the root of your JAR file & you could have that folder persisted into the final container.

Not sure if that helps, but thought I'd follow up.

**Comment by goafabric** [comment]
@dmikusa thank you

**Comment by goafabric** [comment]
@dmikusa sorry to contact you via this issue .. but i don't know another way without raising a new issue
can you tell me what happened to the issue concerning "arm64" support ?
https://github.com/paketo-buildpacks/stacks/issues/51

this was still open and now just has the "repo has been archived now" status
so do we have support now for arm64 ? because last time i tried it did not work ..
also curious concerning spring boot 3.0
thank u

**Comment by dmikusa** [comment]
I suspect that is closed because of project repo changes, not because we have ARM64 support complete. That is still a work in progress.

What we have for ARM64 at the moment is a build-your-own option. See https://github.com/dmikusa/paketo-arm64.

A past colleague at VMware also has a Docker Hub image he's published using these instructions. You can use that, but it's an unofficial image at this point. See [this comment](https://github.com/dmikusa/paketo-arm64/issues/3#issuecomment-1024995644).

There are still plans for official ARM64 support, but it's kind of hung up on some upstream issues that we need to build images in a sustainable way. See [this](https://github.com/buildpacks/pack/issues/1459) and [this](https://github.com/buildpacks/pack/issues/1460). Upvotes on those helps.

**Comment by goafabric** [comment]
@dmikusa thank u very much again
