### ISSUE TITLE
Spring Boot Native Builds with bellsoft-liberica:9.9.0-ea crash since this morning with 403

### ISSUE THREAD

**Issue by goafabric** [paketo-buildpacks/java#826]
Spring Boot 3.0 RC1 brought in Native Image Support requiring Graalvm 22.3.
The task that the spring boot initializer creates creates this gradle configuration:

buildpacks =  ['gcr.io/paketo-buildpacks/bellsoft-liberica:9.9.0-ea', 'gcr.io/paketo-buildpacks/java-native-image']

Worked perfectly fine until this morning now it crashes with the exception below.
Clicking on the link inside the browser also yields to a 403.
Was this version removed ?

` [creator]       BellSoft Liberica NIK 17.0.5: Contributing to layer
    [creator]         Downloading from https://download.bell-sw.com/vm/22.3.0/bellsoft-liberica-vm-core-openjdk17.0.5+8-22.3.0+1-ea-linux-amd64.tar.gz
    [creator]     unable to invoke layer creator
    [creator]     unable to get dependency native-image-svm
    [creator]     unable to download https://download.bell-sw.com/vm/22.3.0/bellsoft-liberica-vm-core-openjdk17.0.5+8-22.3.0+1-ea-linux-amd64.tar.gz
    [creator]     could not download https://download.bell-sw.com/vm/22.3.0/bellsoft-liberica-vm-core-openjdk17.0.5+8-22.3.0+1-ea-linux-amd64.tar.gz: 403
    [creator]     ERROR: failed to build: exit status 1`

**Comment by goafabric** [comment]
seems to be solved .. right now the builds run again

**Comment by dmikusa** [comment]
Apologizes. That happens sometimes when there are issues with vendors.

You can isolate from that a bit if you use dependency mappings. You can pre-download the files & pass them to the build containers via a volume mount. The buildpacks then don't need to make a remote connection when building new images. See [info here](https://paketo.io/docs/howto/configuration/#dependency-mappings). There is also a tool that [automates the process](https://github.com/dmikusa/binding-tool). You can use this as another layer of caching for dependencies.

Since it seems to be resolved. I'm going to close this. If more issues pop up please let us know and we can reach out to the vendor. Thanks!

**Comment by goafabric** [comment]
@dmikusa thank you (as always :) )
